using UnityEditor;
using UnityEngine;

namespace MasterData.Editor
{
    [CreateAssetMenu(fileName = "CSharpGenerateConfig", menuName = "Settings/MasterData Settings", order = 1)]
    public class CSharpGenerateConfigAsset : ScriptableObject
    {
        [Header("自動生成するC#クラスの定義JSONファイルが格納されているフォルダパス")]
        [SerializeField] private string jsonFolderPath = "Assets/MasterData_AutoGenerated";
        [Header("自動生成されたC#クラスを格納するフォルダパス")]
        [SerializeField] private string outputFolderPath = "Assets/App/Scripts/MasterData/AutoGenerated";
        
        [Space(10)]
        [Header("自動生成されたC#クラスのnamespace")]
        [SerializeField] private string autoGeneratedNameSpace;
        
        public string JsonFolderPath => jsonFolderPath;
        public string OutputFolderPath => outputFolderPath;
        
        public string AutoGeneratedNameSpace => autoGeneratedNameSpace;
        
        [MenuItem("Development Tools/MasterData/Config/Create CSharpGenerateConfigAsset", false, 110)]
        public static void CreateCSharpGenerateConfigAsset()
        {
            MasterDataConfigAssetCreator.CreateAssetIfNeeded<CSharpGenerateConfigAsset>("CSharpGenerateConfigAsset");
        }
        
        [MenuItem("Development Tools/MasterData/Config/Select ProjectWindow CSharpGenerateConfigAsset", false, 120)]
        public static void OpenCSharpGenerateConfigAsset()
        {
            MasterDataConfigAssetCreator.OpenOrCreateAsset<CSharpGenerateConfigAsset>("CSharpGenerateConfigAsset");
        }
    }
}