using UnityEditor;
using UnityEngine;

namespace MasterData.Editor
{
    [CreateAssetMenu(fileName = "MasterSheetzConfig", menuName = "MasterSheetz/Create MasterSheetz Config Asset",
        order = 1
    )]
    public class MasterSheetzConfigAsset : ScriptableObject
    {
        [Header("GoogleDriveのリンク")] [TextArea(3, 4)] [SerializeField]
        private string googleDriveLink;

        [Header("MasterDataを格納するフォルダパス")] [SerializeField]
        private string masterDataPath = "";

        [Header("自動生成するC#クラスの定義JSONファイルが格納されているフォルダパス")] [SerializeField]
        private string jsonFolderPath = "Assets/MasterData_AutoGenerated";

        [Header("自動生成されたC#クラスを格納するフォルダパス")] [SerializeField]
        private string outputFolderPath = "Assets/App/Scripts/MasterData/AutoGenerated";

        [Space(10)] [Header("自動生成されたC#クラスのnamespace")] [SerializeField]
        private string autoGeneratedNameSpace;

        public string GoogleDriveLink => googleDriveLink;
        public string MasterDataPath => masterDataPath;
        public string JsonFolderPath => jsonFolderPath;
        public string OutputFolderPath => outputFolderPath;
        public string AutoGeneratedNameSpace => autoGeneratedNameSpace;

        [MenuItem("Development Tools/MasterData/Config/Create MasterSheetzConfigAsset", false, 110)]
        public static void CreateCSharpGenerateConfigAsset()
        {
            MasterDataConfigAssetCreator.CreateAssetIfNeeded<MasterSheetzConfigAsset>(nameof(MasterSheetzConfigAsset));
        }

        [MenuItem("Development Tools/MasterData/Config/Select ProjectWindow MasterSheetzConfigAsset", false, 120)]
        public static void OpenCSharpGenerateConfigAsset()
        {
            MasterDataConfigAssetCreator.OpenOrCreateAsset<MasterSheetzConfigAsset>(nameof(MasterSheetzConfigAsset));
        }
    }
}